### ISSUE TITLE
Syntax Error: SELECT list is not in GROUP BY clause and contains nonaggregated column

### ISSUE THREAD

**Issue by webcourse-ng** [eclectic-bytech/webcourses-ng#23]
After server upgrades, new MySQL version throws error:

`Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'admin_webcourses.UP.progress_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

**Comment by webcourse-ng** [comment]
Removed ONLY_FULL_GROUP_BY from phpMyAdmin -> Variables Tab -> SQL Mode.

**Comment by webcourse-ng** [comment]
Setting had to be changed again May 1.

**Comment by webcourse-ng** [comment]
Occurred again June 13th. Today was a server reboot - cause?

**Comment by webcourse-ng** [comment]
Again.

[Thu Jul 25 09:51:34.442849 2019] [proxy_fcgi:error] [pid 12813] [client 89.73.50.17:33618] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1140 In aggregated query without GROUP BY, expression #5 of SELECT list contains nonaggregated column 'eclectic_brivia.CI.title'; this is incompatible with sql_mode=only_full_group_by in /var/www/vhosts/eclectic.ca/public_html/brivia/api/v1/meta/pid.php:31\nStack trace:\n#0 /var/www/vhosts/eclectic.ca/public_html/brivia/api/v1/meta/pid.php(31): PDOStatement->execute()\n#1 /var/www/vhosts/eclectic.ca/public_html/brivia/api/v1/meta/index.php(17): get_pid_meta('545')\n#2 /var/www/vhosts/eclectic.ca/public_html/brivia/api/v1/user/index.php(11): meta(Array)\n#3 {main}\n  thrown in /var/www/vhosts/eclectic.ca/public_html/brivia/api/v1/meta/pid.php on line 31\n', referer: https://www.eclectic.ca/brivia/my-webcourses
